
x-environment-debug: &env-dev
  DEBUG: "true"
  GUNICORN_LOG_LEVEL: INFO

services:


  devbox: &devbox
    build:
      dockerfile: ./docker/devbox.dockerfile
      context: .
    image: veho-wms/devbox
    environment:
      <<: *env-dev
    volumes:
      - "./:/opt/project"
    command: "service"
    ports:
      - 8000:8000
    networks:
      - veho-wms




########################################
#
# Development Services
#
########################################


  test:
    <<: [ *devbox ]
    command: "test"

  lint:
    <<: [ *devbox ]
    command: "lint"



########################################
#
# External Service / Dependencies
#
########################################





volumes:
  home:
  db:
    driver: local
  data:
    driver: local

networks:
  veho-wms: